# Generated by Django 4.0.4 on 2022-06-03 10:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("uid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("birthday_year", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32)),
                ("authors", models.ManyToManyField(to="authors.author")),
            ],
        ),
        migrations.CreateModel(
            name="Biography",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("author", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="authors.author")),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="authors.author")),
            ],
        ),
    ]
