# Generated by Django 4.0.4 on 2022-05-24 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=64, unique=True, verbose_name='Название проекта')),
                ('repository_link', models.URLField(verbose_name='Ссылка на репозиторий')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, работающие с проектом')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('note_text', models.TextField(max_length=64, verbose_name='Текст заметки')),
                ('date_created', models.DateTimeField(auto_now_add=True, max_length=64, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, max_length=254, verbose_name='Дата обновления')),
                ('execution_status', models.CharField(max_length=64, verbose_name='Статус активности заметки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор заметки')),
                ('project_name', models.ManyToManyField(to='todos.project', verbose_name='Проект, в котором сделана заметка')),
            ],
        ),
    ]
